import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { gql, useLazyQuery } from '@apollo/client'

const inter = Inter({ subsets: ['latin'] })

const getAllLinks = gql`
  query Links {
    links {
      id
      title
      url
      description
      imageUrl
      category
    }
  }
`

export default function Home() {
  const [getLinks, { loading, error, data }] = useLazyQuery(getAllLinks)

  const handleFetch = async () => {
    await getLinks()
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <button onClick={handleFetch}> Get Links </button>
      </main>
    </>
  )
}
